import {
  LuShoppingBag,
  LuHeart,
  LuSearch,
  LuText,
  LuX,
  LuEye,
  LuEyeOff,
  LuArrowLeft,
  LuArrowRight,
  LuTrash2,
  LuPencilLine,
  LuArrowDown,
  LuArrowUp,
  LuChevronLeft,
  LuChevronRight,
  LuChevronDown,
  LuFilter,
  LuMinus,
  LuStar,
  LuPlus,
  LuAlertTriangle,
  LuLogOut,
  LuListOrdered,
} from "react-icons/lu";
import loader from "./loader.svg";
import google from "./google.png";
import lipstick from "./lipstick.png";
import mascara from "./mascara-brush.png";

export {
  LuAlertTriangle,
  LuShoppingBag,
  LuHeart,
  LuSearch,
  LuText,
  LuX,
  LuEye,
  LuEyeOff,
  LuArrowLeft,
  LuTrash2,
  LuPencilLine,
  LuArrowDown,
  LuArrowUp,
  LuChevronLeft,
  LuChevronRight,
  LuChevronDown,
  LuFilter,
  LuMinus,
  LuPlus,
  LuStar,
  LuArrowRight,
  LuLogOut,
  LuListOrdered,
  google,
  loader,
  lipstick,
  mascara,
};
